import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NextIntlProvider from "@/i18n/NextIntlProvider";
import { getMessages } from "next-intl/server";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // For static export, we'll use client-side locale detection
  // The actual locale will be determined by the LanguageSwitcher and stored in localStorage
  const locale = 'zh'; // Default locale for server-side rendering
  const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlProvider messages={messages} locale={locale}>
          {children}
        </NextIntlProvider>
      </body>
    </html>
  );
}
